### ISSUE TITLE
[Suggestion] CommandInterceptor feature

### ISSUE THREAD

**Issue by TheRobLP** [ProjectG-Plugins/CrossplatForms#18]
Good day.

So, what do I mean with CommandInterceptor? Basically, when a user on Bedrock runs a command the CrossplatForms plugin would do something else. For example if you have a GUI plugin for Java players that opens a GUI with the command /server, the CrosplatForms plugin would check if a Bedrock player executes the command, and if so it redirects the user to the Bedrock GUI instead. I hope that is understandable. If not, please feel free to ask me, and I will try my best to clear up any confusion. Thanks in advance for your reply.

Sincerely
Rob

**Comment by Konicai** [comment]
This was planned for the most part in https://github.com/ProjectG-Plugins/CrossplatForms/issues/3. I'll also do a similar thing for access items. 

Currently this could be done with MyCommand and https://github.com/rtm516/FloodgatePlaceholders, however CrossplatForms is eventually going to support other platforms so its not a permanent solution. 

Feel free to join our Discord if you want to talk further or need help.

**Comment by TheRobLP** [comment]
I see. Thank you very much for your response. I am already in the GeyserMC Discord actually. In fact I was talking to one of the developers Tim, and he recommended me to search your Github repo regarding Bedrock GUI's. Many thanks for your reply.

As always; Best Regards
Robin H.

**Comment by Konicai** [comment]
closed in 0e04740f3caf9aee0de6cbabee3e007a7e056604
