### ISSUE TITLE
Action or option to close inventory menu on click

### ISSUE THREAD

**Issue by Konicai** [ProjectG-Plugins/CrossplatForms#75]
### What feature do you want to see added?

An action or an option in each inventory menu to close the menu whenever the player successfully clicks on a button.

### Are there any alternatives?

Run a command that closes the menu

**Comment by Anzo52** [comment]
I'll give it a try if you'd like

**Comment by Konicai** [comment]
PRs are welcome. You can target the `main` branch if you want. I'd suggest creating a field in JavaMenu.class and then checking that value in https://github.com/ProjectG-Plugins/CrossplatForms/blob/main/spigot-common/src/main/java/dev/projectg/crossplatforms/spigot/common/SpigotInterfacerBase.java in the inventory click event

**Comment by Konicai** [comment]
Closed 66a9012
